### ISSUE TITLE
Application Show - Page/Component

### ISSUE THREAD

**Issue by AdamTomczyk** [LofftApp/lofftMobileApp#138]
# Feature Request

### Limiting Branches
The following issues limit this feature, which will need to be closed and added to this branch before it can be added. 
 
- This issue is not limited by other PRs or Issues. 

_Use this form to outline potential new features or planned features in lofft_

## **Feature description**

This Feature is a contiuatnion of the application index where essentialy the use will get to the show page to review its application in details 

### **Todo**

- [] Link new page
- [] Create the frontend
- [] Dynamic Status Bar

### **Potential Challenges**

- Redux needs to be hooked in! (Probably at a later stage though)

## **Design and Figma**

_Latest design is located on the Figma board_

### Screenshots
![application show](https://user-images.githubusercontent.com/86358155/226985728-af6690c4-acc0-41c7-bd5e-5af2d9c70f4d.jpg)
