### ISSUE TITLE
Applicants Page for Landlord

### ISSUE THREAD

**Issue by xxjmsxx** [LofftApp/lofftMobileApp#163]
# Feature Request
- Applicants Page Base Design
### Limiting Branches
The following issues limit this feature, which will need to be closed and added to this branch before it can be added. 
 
- This issue is not limited by other PRs or Issues. 

_Use this form to outline potential new features or planned features in lofft_

## **Feature description**
- Page that shows each applicant with their corresponding match/data
### **Feature experience**
-as a landlord i should be able to click on each of my applicants and receive more information.
- be able to set a filter for

-

### **Todo**

- [ ] create basic design
- [ ] make applicants selectable
- [ ] link filter button
### **Potential Challenges**

- 

## **Design and Figma**

_Latest design is located on the Figma board_
