### ISSUE TITLE
Link up the apple and google sign in with API

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofftMobileApp#193]
# Feature Request

### Limiting Branches
The following issues limit this feature, which will need to be closed and added to this branch before it can be added. 
 

- This issue is not limited by other PRs or Issues. 

_Use this form to outline potential new features or planned features in lofft_

## **Feature description**
The Google and Apple sign in buttons need to be linked to the API. 

### **Todo**

- [ ] Uncomment the buttons
- [ ] Link up through the auth slice to the API
- [ ] Capture the response and store it as a token. 
- [ ] Add the condition that the Apple button is only visible on apple devices and not android. 

### **Potential Challenges**

-

## **Design and Figma**

_Latest design is located on the Figma board_
