### ISSUE TITLE
Language Page Bug Fixes / TouchUps

### ISSUE THREAD

**Issue by xxjmsxx** [LofftApp/lofftMobileApp#222]
# Quick Fix

_Quick fixes are small issues that can be completed during other development phases, to complete one just add it as closed to the unrelated PR and add your name as dev_

## Details

_A description of what needs changing, add which page or how to get there or if it's a component_

## To-do

- [x] I still need to remove the language from the search bar when its selected
- [ ] change to the correct icon
- [ ] add pagination to the bottom of the page for user sign up
- [ ] create landlord version / pass props
- [ ] connect continue button to next step
