### ISSUE TITLE
Signup & Registration Process

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofftMobileApp#3]
## Overview
This is the initial development of the sign in, sign up process for lofft. The result is that a user will be able to view the home landing page as per the designs in Figma. The end goal is to a blank page where the user is signed in, this will allow for the development of the next two user journeys. 

## Todo
- [x] Set the splash screen when the application loads, there is reference to this in the original mobile app path. 
- [x] The first page that loads is for a user to create their account, if a user has an account then they will the option to Sign in. 
- [x] A user will also have the option to sign up and Sign in with Apple and Google this is handled by firebase. 
- [x] The final page will require a user to select their purpose to using the app.
