### ISSUE TITLE
Lofft finding user registration flow - after registration

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofftMobileApp#4]
## Overview
Once the user signs in and registers the user is approached by a series of options and questions, this will require the user to set their personal profile to enhance their experience in looking for and application. 

**Blocked by:** #3 

## Todo
- [x] Build the Tell us a bit about your self
- [x] Create a tag or bill icon that will take the data of what the user is saying about themselves
 - *Think of the DB design and how this will be presented in the DB.*
   - [x] Create an interaction where the user will select the buttons. 
- [x] Build the page for a user to select their gender identity
- [x] Build the flow for where the user will select their desired city or neighbourhood. 
- [x] Choose an option for the user to select their budget. 
- [x] Allow a user to select their ideal flat
- [x] Build a user description section where the user can will describe themselves.
