### ISSUE TITLE
Initial landing Map View

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofftMobileApp#41]
# Feature Request

_Use this form to outline potential new features or planned features in lofft_

## **Feature description**
*  A Map to show the apartments. 

### **Feature experience**

- As a `Visitor` I can see the location of the apartment
- As a `visitor` I can see key details about the lofft

### **Todo**

- [x] Add Mapbox to the app
- [ ] Show icons of the apartment with their percentage score. 
- [ ] Show the individual loffts in a side scroll at the bottom of the screen. 
- [ ] Details of the lofft should appear in the side scroll container. @DonJuanKim has completed a similar task on the list screen, maybe this could be updated to suit the map view. 

### **Potential Challenges**

- Mapbox

## **Link to Figma board, images and design description**

_Latest design is located on the figma board_

**[Figma board]()**

### Design Description
![Screenshot 2022-12-07 at 18 54 12](https://user-images.githubusercontent.com/5392107/206258554-7ea1b3bc-0bea-49e2-a351-d5ba6ecf49f8.png)
