### ISSUE TITLE
Clean up navigation into seperate files

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofftMobileApp#46]
The navigation is currently long and messy; this should be cleaned up into their own separate files for logged out, user journey and user screens. 

### Todo
- [x] Add a file for logged out screens
- [ ] Add a file for initial user journey screens
- [ ] Add a file for finder journey screens
- [ ] Add a file for renter journey screens
