### ISSUE TITLE
Posting a flat reg flow

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofftMobileApp#5]
## Overview
This is the user registration flow, that will require a user to save their details if they wish to post their room to the platform. The user will answer a series of questions to establish the accommodation. 

**Blocked By:** #3 

## Todo
- [ ] Create page to add the address to the application and how much it will cost
- [ ] Create page to list the available from and to dates or if the property is a perminant let. 
- [ ] Create a page using pills (Created by @Nat-Ma in issue: #4 ) to list the features and core details of the room. 
- [ ] Create a page using pills that show who the appartment is ideal for at the ideals within appartment. 
- [ ] Create a page to allow a user to upload photos. 
- [ ] End the flow with the user aggreeing to the TnC and the policy of lofft.
