### ISSUE TITLE
`Today` and `Perminant` should be active when clicked

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofftMobileApp#71]
# Quick Fix
_Quick fixes are small issues that can be completed during other development phases. To complete one just add it as close to the unrelated PR and add your name as dev_

## Details
 
In the flat creation journey on the date picker page, the two buttons `Today` and `permanent` just populate the date fields, though this should when active be lavender 100 and not populate the date fields. On the addition of another date then these buttons should deactivate. 

## To-do
- [ ] Set the `today` button to lavender when active. 
- [ ] Set the `permanent` button to lavender when active .
- [ ] When the buttons are pressed any associated dates should be cleared or updated. 
- [ ] When a date has been added to the input fields then the buttons should deactivate. 

## Notes
![Simulator Screen Shot - iPhone 14 Pro - 2022-12-29 at 16 16 06](https://user-images.githubusercontent.com/5392107/209980324-a6f90a41-62e5-45c9-87c7-2ff0254e57c2.png)

This is an easy task and would be a good first issue. @xxjmsxx, if you would like to take this on, would be an easy start. We can do this together or you could do it with @DonJuanKim.
