### ISSUE TITLE
Highlighted Buttons [Back Button, Heart]

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofftMobileApp#90]
# Feature Request

_Use this form to outline potential new features or planned features in lofft_
The back buttons on the Lofft add a page to have a white background, highlighting them from the image.

### **Feature experience**

- As a `user`, I can navigate back to the map or previous page through the app back button
- As a `user`, I can add the current Lofft to my wishlist. 

### **Todo**

- [x] Create a page called `HighlithgtedButton.tsx`
- [x] Create a method that takes a `onPress` action.
- [x] Import LofftIcons into the page. 

### **Potential Challenges**

-

## **Design and Figma**

_Latest design is located on the Figma board_

### Screenshots
<img width="50" alt="Screenshot 2023-01-12 at 18 29 31" src="https://user-images.githubusercontent.com/5392107/212137630-7fc86789-0dce-4d3e-8096-b0a5142fefed.png">

<img width="50" alt="Screenshot 2023-01-12 at 18 29 40" src="https://user-images.githubusercontent.com/5392107/212137655-3f44d28b-b9a0-48ec-ae76-49d5ea9adcab.png">

### Additional context

Please feel free to add any other context or screenshots about the feature request here.
