### ISSUE TITLE
Header Photo Lofft Profile

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofftMobileApp#91]
# Feature Request

### Limiting Branches
The following issues limit this feature, which will need to be closed and added to this branch before it can be added. 
- #90 

_Use this form to outline potential new features or planned features in lofft_

The top section of the Lofft contains an image, including a pagination bar and images the user has uploaded. 

### **Feature experience**

- As a `user`, I can view photos of the Lofft
- As a `user`, I can change the photo by swiping left or right.
- As a `user`, I can use the heart icon to add the Lofft to my favourites.  

### **Todo**

- [ ] Add a `Flat List` component that takes the images. 
- [ ] Add the Pagination Bar component to the bottom of the images. 
- [ ] Add the back and heart icons to the top of the section. 
- [ ] Ensure the images reach the corners of the screen top and bottom. 

### **Potential Challenges**

- The flat list may pose some issues. 
- This should be completed by someone more experienced or with peer programming.

## **Design and Figma**

_Latest design is located on the Figma board_

### Screenshots
<img width="574" alt="Screenshot 2023-01-12 at 23 10 31" src="https://user-images.githubusercontent.com/5392107/212192000-76aec0d8-d88a-4d47-a3f5-d52dcfb2703a.png">

### Design Description
A top panel with back buttons and heart icons.
