### ISSUE TITLE
Expandable text block

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofftMobileApp#92]
# Feature Request

_Use this form to outline potential new features or planned features in lofft_

This is a text block with a button that allows it to be expanded, a component that will form part of the pages. 

### **Feature experience**

- As a `user`, I can read a block of text; if it overflows, then I can press see more to see the rest of the text. 

### **Todo**

- [ ] Detect if the block of text is expanding beyond the boundaries of the container, 
- [ ] If the block is, the see more button should be visible. 
- [ ] When the user presses the button, the boundaries of the box expand to show the text content. 
- [ ] When expanded, a `show less` button should be visible. 

### **Potential Challenges**

- Formatting the text may pose some challenges. 

## **Design and Figma**

_Latest design is located on the Figma board_

### Screenshots
<img width="496" alt="Screenshot 2023-01-12 at 23 17 42" src="https://user-images.githubusercontent.com/5392107/212193045-a38f96e9-0103-4b79-943c-11f741d70f0a.png">

### Design Description
This is a block of text, that is adjustable to the size of the information.
