### ISSUE TITLE
User Profile page

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofftMobileApp#94]
# Feature Request

### Limiting Branches
The following issues limit this feature, which will need to be closed and added to this branch before it can be added. 
 
- #90 
- #91 
- #92 
- #93 

_Use this form to outline potential new features or planned features in lofft_

## **Feature description**
This is the mane add view, showing the apartment to the potential user to apply for. This is the visual application, and the backend and logic will be applied through the submit button. 

### **Feature experience**

- As a `user`, I can view essential information about the Lofft. 
- As a `user`, I can push the apply button to apply for this Lofft. 
- As a `user`, I can see the length of time this lofft is available. 

### **Todo**

- [ ] Combine the components that are being created for this page. 
- [ ] Add the additional components such as the core button and lofft information block. 
- [ ] Add the Navigation for the back button. 
- [ ] Add the save button logic (This should be created in a separate PR)

### **Potential Challenges**

- This combines multiple components being created for this page; some modifications may be required to make it work. 
- This should be completed by a more experienced dev or with a junior as peer programming. 

## **Design and Figma**

_Latest design is located on the Figma board_

### Screenshots
<img width="224" alt="Screenshot 2023-01-12 at 23 29 18" src="https://user-images.githubusercontent.com/5392107/212194620-3f1cfef0-0f49-4abe-a689-f50b20acbee9.png">
