### ISSUE TITLE
Application Success Page  

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofftMobileApp#95]
# Feature Request

### Limiting Branches
The following issues limit this feature, which will need to be closed and added to this branch before it can be added. 

 
- #94 

_Use this form to outline potential new features or planned features in lofft_

## **Feature description**
Once the user pushes the application button, and their profile is complete, they should be brought to this page, allowing them to navigate back to search or to their applications. 

### **Feature experience**

- As an `applicant`, I can see a confirmation page. 
- As an `applicant`, I can navigate to all applications or the search pages. 

### **Todo**

- [ ] Creat a new page adding the text and icons. 
- [ ] Access the number of remaining tokens to be shown to the user. 
- [ ] Add the core button primary to allow a user to navigate to applications 
- [ ] Add the core button inverted to allow users to go back to searches. 

### **Potential Challenges**

- The background is proving to be a challenge. 

## **Design and Figma**

_Latest design is located on the Figma board_

### Screenshots
<img width="210" alt="Screenshot 2023-01-12 at 23 34 12" src="https://user-images.githubusercontent.com/5392107/212195781-f29280e2-bf17-4aaf-9d8e-dfd1c6e4d87c.png">
