### ISSUE TITLE
Pop Modal directing the user to finish their profile

### ISSUE THREAD

**Issue by jhibbeard89** [LofftApp/lofftMobileApp#96]
# Feature Request
This modal will pop up if their profile needs to be completed and allow them to complete it to increase the chances they will be successful.

### Limiting Branches
The following issues limit this feature, which will need to be closed and added to this branch before it can be added. 
 
- #94 

_Use this form to outline potential new features or planned features in lofft_

### **Feature experience**

- As an `applicant`, I can see a pop to allow me to complete my profile or later. 

### **Todo**

- [ ] Use the modal and create a new component to show this page. 
- [ ] Add the (x) to the top right to allow the model to be closed, resulting in the application being cancelled. 
- [ ] Add the Primary core button to allow the user to complete the application. 
- [ ] Add the inverted button to allow the user to complete it later. 

### **Potential Challenges**

- The blurring of the page will require some research; we do not currently have this in our application. 

## **Design and Figma**

_Latest design is located on the Figma board_

### Screenshots
<img width="226" alt="Screenshot 2023-01-12 at 23 37 57" src="https://user-images.githubusercontent.com/5392107/212196292-a0876401-2e6c-4fad-bac2-83f63ed481e0.png">
